# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Kem CoBa Line' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kem CoBa Line
  pod 'SwiftGifOrigin', '~> 1.5'

  target 'Kem CoBa LineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Kem CoBa LineUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
